name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  packages:
    runs-on: ubuntu-24.04
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v5

      - name: ğŸ— Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: ğŸ” Check packages types
        run: npm run check-types

      - name: âœ… Lint packages
        run: npm run lint

      - name: ğŸ‘· Build packages
        run: npm run build

      - name: ğŸ§ª Test packages
        run: npm run test
